# Site settings
title: Emperial.sg SkillTree Simulator for Blade & Soul Taiwan
email: avengerx@emperial.sg
description: > # this means to ignore newlines until "baseurl:"
  Translated Blade and Soul Skill Trees for English-Speaking Players
baseurl: "/skilltree/" # the subpath of your site, e.g. /blog/
url: "http://skilltree.emperial.com" # the base hostname & protocol for your site

# Build settings
markdown: redcarpet
sass:
  style: compressed
